### ISSUE TITLE
Submit the date via the form

### ISSUE THREAD

**Issue by HaoyangFan96** [fengyuanchen/datepicker#166] opened 2018-07-06 01:32 UTC
I am adapting the code according to [this](https://github.com/fengyuanchen/datepicker/blob/master/examples/datepicker-in-modal.html) into my own application

I also add another datepicker, so there are two datepickers in total and I wrap them into a form, with GET request specified

In the footer, I add a button which is used to submit the values that are picked in the two datepicker, however, when I test it on Chrome, nothing happens and the form apparently hasn't been submitted at all. Any idea?

```
    <!-- Modal -->
    <div class="modal fade" id="modal" role="dialog" aria-labelledby="modalLabel" tabindex="-1">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="modalLabel">Datepicker</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <form action='/date.php' method="GET" id="datepickerform">
              <fieldset>
                <label for="startdate">Start Date:</label>
                <input id="startdate" name="startdate" type="text" class="form-control" data-toggle="datepicker">
              </fieldset>
              <fieldset style="padding-top: 10px">
                <label for="enddate">End Date:</label>
                <input id="enddate" name="enddate" type="text" class="form-control" data-toggle="datepicker">
              </fieldset>
            </form>
          </div>
          <div class="modal-footer">
            <button type="submit" form="datepickerform" value="Submit" class="btn btn-secondary" data-dismiss="modal">Submit</button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
  </div>
```
Thanks in advance

**Comment by HaoyangFan96** [comment] 2018-07-06 06:39
Update:
it looks like the attribute of the submit button `data-dismiss="modal"` conflicts with another attribute `form="datepickerform"` which is used to specify the owner form of this button

if I change the submit button from 

```
<button type="submit" form="datepickerform" value="Submit" class="btn btn-secondary" data-dismiss="modal">Submit</button>
```
to
```
<button type="submit" form="datepickerform" value="Submit" class="btn btn-secondary">Submit</button>
```
then the form can be successfully submitted? Any idea on the reason behind that?

**Comment by webdo** [comment] 2018-08-09 00:08
It may be a bit late.

The problem isn't with the datepicker but with your submit button itself.
Bootstrap dismiss the modal before the form can be sent.

You need to use javascript to either send the form once the modal closes, or close the modal once the form is sent.

Closing the modal once the form is sent: 

`$( "#sendDatePickerForm" ).submit(function( event ) {
$('#modal').modal('close');
});`

**Comment by webdo** [comment] 2018-08-09 00:26
It may be a bit late.

The problem isn't with the datepicker but with your submit button itself.
Bootstrap dismiss the modal before the form can be sent.

You need to use javascript to either send the form once the modal is closed, or close the modal once the form is sent.

Closing the modal once the form is sent could be done with something like that:

$( "#datepickerform" ).submit(function( event ) { $('#modal').modal('close'); });

**Comment by webdo** [comment] 2018-08-09 00:27
It may be a bit late.

The problem isn't with the datepicker but with your submit button itself.
Bootstrap dismiss the modal before the form can be sent.

You need to use javascript to either submit the form once the modal is closed, or close the modal once the form is submited.

Closing the modal once the form is submited could be done with something like that:

$( "#datepickerform" ).submit(function( event ) { $('#modal').modal('close'); });

**Closed** 2018-08-25 07:32 UTC
